config/routes.rb
Rails.application.routes.draw do
  resources :company1s do
    collection {post :import}
  end
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  get 'welcome/features'

  get 'welcome/pricing'

  resources :invoices
  root to: 'welcome#index'
end

app/models/company1.rb
class Company1 < ActiveRecord::Bas
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company1.create!= row.to_hash
      end
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/invoice_search.rb
class InvoiceSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
 end

  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  private

  def parsed_date(data_string, default)
    Date.parse(data_string)
  rescue ArgumentError, TypeError
    default
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/company1s_controller.rb
class Company1sController < ApplicationController
  before_action :set_company1, only: [:show, :edit, :update, :destroy]

  # GET /company1s
  # GET /company1s.json
  def index
    @company1s = Company1.all
  end

  # GET /company1s/1
  # GET /company1s/1.json
  def show
  end

  # GET /company1s/new
  def new
    @company1 = Company1.new
  end

  # GET /company1s/1/edit
  def edit
  end

  # POST /company1s
  # POST /company1s.json
  def create
    @company1 = Company1.new(company1_params)

    respond_to do |format|
      if @company1.save
        format.html { redirect_to @company1, notice: 'Company1 was successfully created.' }
        format.json { render :show, status: :created, location: @company1 }
      else
        format.html { render :new }
        format.json { render json: @company1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company1s/1
  # PATCH/PUT /company1s/1.json
  def update
    respond_to do |format|
      if @company1.update(company1_params)
        format.html { redirect_to @company1, notice: 'Company1 was successfully updated.' }
        format.json { render :show, status: :ok, location: @company1 }
      else
        format.html { render :edit }
        format.json { render json: @company1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company1s/1
  # DELETE /company1s/1.json
  def destroy
    @company1.destroy
    respond_to do |format|
      format.html { redirect_to company1s_url, notice: 'Company1 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def import
    Company1.import(params[:file])
    redirect_to company1s_path, notice "company was added successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company1
      @company1 = Company1.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company1_params
      params.require(:company1).permit(:name, :manager, :status, :terms)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :salesperson, :company, :tax)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

  def features
  end

  def pricing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company1s_helper.rb
module Company1sHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/company1s/_form.html.erb
<%= form_for(@company1) do |f| %>
  <% if @company1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company1.errors.count, "error") %> prohibited this company1 from being saved:</h2>

      <ul>
      <% @company1.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manager %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :terms %><br>
    <%= f.number_field :terms %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company1s/edit.html.erb
<h1>Editing Company1</h1>

<%= render 'form' %>

<%= link_to 'Show', @company1 %> |
<%= link_to 'Back', company1s_path %>

app/views/company1s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Company1s</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manager</th>
      <th>Status</th>
      <th>Terms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company1s.each do |company1| %>
      <tr>
        <td><%= company1.name %></td>
        <td><%= company1.manager %></td>
        <td><%= company1.status %></td>
        <td><%= company1.terms %></td>
        <td><%= link_to 'Show', company1 %></td>
        <td><%= link_to 'Edit', edit_company1_path(company1) %></td>
        <td><%= link_to 'Destroy', company1, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3>import companies</h3>
<%= form_tag import_company1s_path multipart : true do %>
<%= file_field_tag :file %>
<%= submit_tag "upload companies file" %>
<% end %>

<%= link_to 'New Company1', new_company1_path %>

app/views/company1s/new.html.erb
<h1>New Company1</h1>

<%= render 'form' %>

<%= link_to 'Back', company1s_path %>

app/views/company1s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company1.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @company1.manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company1.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @company1.terms %>
</p>

<%= link_to 'Edit', edit_company1_path(@company1) %> |
<%= link_to 'Back', company1s_path %>

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :salesperson %><br>
    <%= f.text_field :salesperson %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :tax %><br>
    <%= f.text_field :tax %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="pull-right range-query">
  <%= form_tag invoices_path, method: :get do%>
    <%= text_field_tag 'search[date_from]', @search.date_from %>
    <%= text_field_tag 'search[date_to]', @search.date_to %>
    <%= submit_tag 'Search', class: 'btn btn-search' %>
  <% end %>
  </div>
</div>
<h1>Listing Invoices</h1>
<div class="media">
<div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Salesperson</th>
      <th>Company</th>
      <th>Tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.date.strftime("%Y-%m-%d") %></td>
        <td><%= invoice.salesperson %></td>
        <td><%= invoice.company %></td>
        <td><%= invoice.tax %></td>
        <td><%= link_to 'Show', invoice, class: 'btn btn-mini'  %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-mini btn btn-success' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>
<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.salesperson %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Company</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About us", welcome_about_path %></li>
      <li><%= link_to "FAQs", welcome_faq_path %></li>
      <li><%= link_to "Features", welcome_features_path %></li>
      <li><%= link_to "Pricing", welcome_pricing_path %></li>
      <li><%= link_to "Invoices", invoices_path %></li>
      <li><%= link_to "Log In", root_path %></li>
    </ul>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>